/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaterialSymbolsChevronLeft: typeof import('~icons/material-symbols/chevron-left')['default']
    IMaterialSymbolsChevronRight: typeof import('~icons/material-symbols/chevron-right')['default']
    IMaterialSymbolsDarkMode: typeof import('~icons/material-symbols/dark-mode')['default']
    IMaterialSymbolsDownload: typeof import('~icons/material-symbols/download')['default']
    IMaterialSymbolsKey: typeof import('~icons/material-symbols/key')['default']
    IMaterialSymbolsLanguage: typeof import('~icons/material-symbols/language')['default']
    IMaterialSymbolsLightMode: typeof import('~icons/material-symbols/light-mode')['default']
    IMaterialSymbolsManage_search: typeof import('~icons/material-symbols/manage_search')['default']
    IMaterialSymbolsManageSearch: typeof import('~icons/material-symbols/manage-search')['default']
    IMaterialSymbolsSearch: typeof import('~icons/material-symbols/search')['default']
    IMaterialSymbolsSettingsOutline: typeof import('~icons/material-symbols/settings-outline')['default']
    IMaterialSymbolsTableViewOutline: typeof import('~icons/material-symbols/table-view-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TranslationQuery: typeof import('./src/components/TranslationQuery.vue')['default']
    TranslationTable: typeof import('./src/components/TranslationTable.vue')['default']
  }
}
