/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IFa6BrandsGithub: typeof import('~icons/fa6-brands/github')['default']
    IMaterialSymbolsArrowBack: typeof import('~icons/material-symbols/arrow-back')['default']
    IMaterialSymbolsArrowForward: typeof import('~icons/material-symbols/arrow-forward')['default']
    IMaterialSymbolsCheck: typeof import('~icons/material-symbols/check')['default']
    IMaterialSymbolsChevronLeft: typeof import('~icons/material-symbols/chevron-left')['default']
    IMaterialSymbolsChevronRight: typeof import('~icons/material-symbols/chevron-right')['default']
    IMaterialSymbolsContentCopy: typeof import('~icons/material-symbols/content-copy')['default']
    IMaterialSymbolsDarkMode: typeof import('~icons/material-symbols/dark-mode')['default']
    IMaterialSymbolsDownload: typeof import('~icons/material-symbols/download')['default']
    IMaterialSymbolsKey: typeof import('~icons/material-symbols/key')['default']
    IMaterialSymbolsLanguage: typeof import('~icons/material-symbols/language')['default']
    IMaterialSymbolsLightMode: typeof import('~icons/material-symbols/light-mode')['default']
    IMaterialSymbolsManageSearch: typeof import('~icons/material-symbols/manage-search')['default']
    IMaterialSymbolsQuiz: typeof import('~icons/material-symbols/quiz')['default']
    IMaterialSymbolsSearch: typeof import('~icons/material-symbols/search')['default']
    IMaterialSymbolsSettingsOutline: typeof import('~icons/material-symbols/settings-outline')['default']
    IMaterialSymbolsShare: typeof import('~icons/material-symbols/share')['default']
    IMaterialSymbolsStar: typeof import('~icons/material-symbols/star')['default']
    IMaterialSymbolsStarHalf: typeof import('~icons/material-symbols/star-half')['default']
    IMaterialSymbolsStars: typeof import('~icons/material-symbols/stars')['default']
    IMaterialSymbolsTable: typeof import('~icons/material-symbols/table')['default']
    IMaterialSymbolsTableViewOutline: typeof import('~icons/material-symbols/table-view-outline')['default']
    IMaterialSymbolsTimer: typeof import('~icons/material-symbols/timer')['default']
    LanguageSelector: typeof import('./src/components/Query/LanguageSelector.vue')['default']
    PageNav: typeof import('./src/components/PageNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableHeader: typeof import('./src/components/Table/TableHeader.vue')['default']
    TablePagination: typeof import('./src/components/Table/TablePagination.vue')['default']
    TranslationQuery: typeof import('./src/components/TranslationQuery.vue')['default']
    TranslationQuiz: typeof import('./src/components/TranslationQuiz.vue')['default']
    TranslationQuizSub: typeof import('./src/components/TranslationQuizSub.vue')['default']
    TranslationTable: typeof import('./src/components/TranslationTable.vue')['default']
  }
}
