name: Lint Code Base
permissions:
  contents: write

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  run-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          FIX_CSS: true
          FIX_JSON: true
          FIX_JAVASCRIPT_ES: true
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_TYPESCRIPT_ES: true
          FIX_TYPESCRIPT_PRETTIER: true
          DEFAULT_BRANCH: 'master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
