name: Lint Code Base
permissions:
  contents: read

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  run-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: 'master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
